controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
dashboard:
    path: /admin
    controller: App\Controller\Admin\AdminController::index