<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerQloX3Op\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQloX3Op/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQloX3Op.legacy');
=======
if (\class_exists(\ContainerHrVg9qJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHrVg9qJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHrVg9qJ.legacy');
>>>>>>> Admin_Dashboard

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerQloX3Op\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQloX3Op\App_KernelDevDebugContainer([
    'container.build_hash' => 'QloX3Op',
    'container.build_id' => '81ae34bb',
    'container.build_time' => 1675272039,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQloX3Op');
=======
    \class_alias(\ContainerHrVg9qJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHrVg9qJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'HrVg9qJ',
    'container.build_id' => '664dcae4',
    'container.build_time' => 1675284431,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHrVg9qJ');
>>>>>>> Admin_Dashboard
