<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHrVg9qJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHrVg9qJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHrVg9qJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHrVg9qJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHrVg9qJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'HrVg9qJ',
    'container.build_id' => 'b5999960',
    'container.build_time' => 1675273239,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHrVg9qJ');
